import { Inter, Outfit } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
// import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import "../../public/service.css";
import '/public/hub.css'
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import BodyClassWrapper from "@/utils/BodyClassWrapper";
import Addresshome from "@/components/homeComponents/12Addresshome";
import DynamicContact from "@/utils/DynamicContact";
// import AddressChange from "@/components/homeComponents/12AddressChange";
import Script from "next/script";

// Import the Inter and Outfit fonts
export const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-inter",
});

export const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  display: "swap",
  variable: "--font-outfit",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};



export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${outfit.variable}`}>
      <head>
        <meta name="google-site-verification" content="HBSffUhqLmjL_SyultPiEJ33DSc-3x39LXSVJOOh4ZY" />
        <link rel="canonical" href="https://webguruz.in" />
        <Script src="https://www.googletagmanager.com/gtag/js?id=G-GX9DH5XMG1" strategy="afterInteractive" />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-GX9DH5XMG1');
          `}
        </Script>  {/* Add JSON-LD for Organization */}
        <Script id="organization-ldjson" type="application/ld+json" strategy="afterInteractive">
          {`
            {
              "@context": "https://schema.org",
              "@type": "Organization",
              "name": "WebGuruz Technologies Pvt Ltd",
              "url": "https://webguruz.in/",
              "logo": "https://webguruz.in/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fheader-logo-one.f806d280.webp&w=256&q=75",
              "contactPoint": [{
                "@type": "ContactPoint",
                "telephone": "+91 708 723 3361",
                "contactType": "customer service",
                "contactOption": "TollFree",
                "areaServed": "IN",
                "availableLanguage": "en"
              },{
                "@type": "ContactPoint",
                "telephone": "+44 758 841 8605",
                "contactType": "customer service",
                "contactOption": "TollFree",
                "areaServed": "GB",
                "availableLanguage": "en"
              },{
                "@type": "ContactPoint",
                "telephone": "+1 (571) 662-8059",
                "contactType": "customer service",
                "contactOption": "TollFree",
                "areaServed": "US",
                "availableLanguage": "en"
              }],
              "sameAs": [
                "https://www.facebook.com/webguruztechnologies",
                "https://twitter.com/Webguruz",
                "https://www.instagram.com/webguruz",
                "https://www.youtube.com/channel/UC-xaX1FJWj40ED-cTm2Lq6w",
                "https://www.linkedin.com/company/webguru-technologies-pvt.-ltd.",
                "https://in.pinterest.com/webguruz"
              ]
            }
          `}
        </Script>

        {/* Add JSON-LD for WebSite */}
        <Script id="website-ldjson" type="application/ld+json" strategy="afterInteractive">
          {`
            {
              "@context": "https://schema.org/",
              "@type": "WebSite",
              "name": "WebGuruz Technologies Pvt Ltd",
              "url": "https://webguruz.in/",
              "potentialAction": {
                "@type": "SearchAction",
                "target": "{search_term_string}",
                "query-input": "required name=search_term_string"
              }
            }
          `}
        </Script>

        {/* Add JSON-LD for LocalBusiness */}
        <Script id="localbusiness-ldjson" type="application/ld+json" strategy="afterInteractive">
          {`
            {
              "@context": "https://schema.org",
              "@type": "LocalBusiness",
              "name": "WebGuruz Technologies Pvt Ltd",
              "image": "https://webguruz.in/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fheader-logo-one.f806d280.webp&w=256&q=75",
              "url": "https://webguruz.in",
              "telephone": "+91 708 723 3361",
              "address": {
                "@type": "PostalAddress",
                "streetAddress": "C-205, 4th Floor, SM Heights NH 5, Sector 74",
                "addressLocality": "Mohali",
                "postalCode": "160071",
                "addressCountry": "IN"
              },
              "geo": {
                "@type": "GeoCoordinates",
                "latitude": 30.7076277,
                "longitude": 76.6828906
              },
              "openingHoursSpecification": {
                "@type": "OpeningHoursSpecification",
                "dayOfWeek": [
                  "Monday",
                  "Tuesday",
                  "Wednesday",
                  "Thursday",
                  "Friday",
                  "Saturday",
                  "Sunday"
                ],
                "opens": "00:00",
                "closes": "23:59"
              },
              "sameAs": [
                "https://www.facebook.com/webguruztechnologies",
                "https://twitter.com/Webguruz",
                "https://www.instagram.com/webguruz",
                "https://www.youtube.com/channel/UC-xaX1FJWj40ED-cTm2Lq6w",
                "https://www.linkedin.com/company/webguru-technologies-pvt.-ltd.",
                "https://in.pinterest.com/webguruz"
              ]
            }
          `}
        </Script>
      </head>
      <body>
        <BodyClassWrapper />
        <Header />
        {children}
        <DynamicContact />
        <Addresshome />
        {/* <AddressChange/> */}
        <Footer />
      </body>
    </html>
  );
}
