import { Inter, Outfit } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.css';
// import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import "../../public/service.css";
import '/public/hub.css'
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import BodyClassWrapper from "@/utils/BodyClassWrapper";
import Addresshome from "@/components/homeComponents/12Addresshome";
import DynamicContact from "@/utils/DynamicContact";
import AddressChange from "@/components/homeComponents/12AddressChange";

// Import the Inter and Outfit fonts
export const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-inter",
});

export const outfit = Outfit({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  display: "swap",
  variable: "--font-outfit",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};



export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${outfit.variable}`}>
      <head>
      <meta name="google-site-verification" content="HBSffUhqLmjL_SyultPiEJ33DSc-3x39LXSVJOOh4ZY" />
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-GX9DH5XMG1"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-GX9DH5XMG1');
            `,
          }}
        />
      </head>
     
      {/* Add both font classes */}
      <body>
        <BodyClassWrapper />
        <Header />
        {children}
        <DynamicContact />
        <Addresshome />
        <AddressChange/>
        <Footer />
      </body>
      
    </html>
  );
}
